name: deepsolo_wsl
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.9.1=hac33072_0
  - blas=1.0=mkl
  - brotli=1.2.0=h27d5ac6_0
  - brotli-bin=1.2.0=h1421c7b_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - cudatoolkit=11.1.1=hb139c0e_13
  - cython=3.0.11=py38h5eee18b_0
  - cytoolz=0.12.2=py38h5eee18b_0
  - dask-core=2023.4.1=py38h06a4308_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.3=h3385a95_0
  - ffmpeg=4.2.2=h20bf706_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - fsspec=2024.6.1=py38h06a4308_0
  - geos=3.8.0=he6710b0_0
  - giflib=5.2.2=hd590300_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - harfbuzz=4.3.0=hf52aaf7_1
  - icu=58.2=he6710b0_3
  - imageio=2.33.1=py38h06a4308_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libbrotlicommon=1.2.0=h32cd6e7_0
  - libbrotlidec=1.2.0=ha2c5f68_0
  - libbrotlienc=1.2.0=h2e96acb_0
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.4=h5eee18b_0
  - libopenvino=2024.4.0=hac27bb2_2
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_2
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_2
  - libopenvino-onnx-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-paddle-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h6481b9d_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.51=h421ea60_0
  - libprotobuf=5.28.2=h5b01275_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.3.1=hb25bd0a_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.4=hcb278e6_0
  - matplotlib-base=3.6.2=py38h945d387_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - ninja=1.13.2=h171cf75_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - partd=1.4.1=py38h06a4308_0
  - pcre2=10.46=h1321c63_0
  - pip=24.2=py38h06a4308_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.14=h59595ed_0
  - pyqt=5.9.2=py38h05f1152_4
  - python=3.8.18=h7a1cb2a_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=py3.8_cuda11.1_cudnn8.0.5_0
  - pywavelets=1.4.1=py38h5eee18b_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.3=hc2a1206_0
  - scikit-image=0.15.0=py38he6710b0_0
  - setuptools=75.1.0=py38h06a4308_0
  - shapely=2.0.1=py38h0fbb895_0
  - sip=4.19.13=py38h295c915_0
  - snappy=1.2.2=h03e3b7b_1
  - sqlite=3.51.0=h2a70700_0
  - svt-av1=2.2.1=h5888daf_0
  - tbb=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - toolz=0.12.0=py38h06a4308_0
  - torchaudio=0.9.0=py38
  - torchvision=0.10.0=py38_cu111
  - tornado=6.4.1=py38h5eee18b_0
  - typing_extensions=4.12.2=pyha770c72_0
  - unicodedata2=15.1.0=py38h5eee18b_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.46=hd8ed1ab_0
  - wheel=0.44.0=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - x265=3.5=h924138e_3
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.4.9=haebb681_0
  - pip:
      - absl-py==2.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - black==21.4b2
      - cachetools==5.5.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - detectron2==0.6+cu111
      - editdistance==0.8.1
      - filelock==3.16.1
      - fonttools==4.57.0
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - idna==3.11
      - imagehash==4.3.2
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iopath==0.1.9
      - kiwisolver==1.4.7
      - llvmlite==0.39.1
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mypy-extensions==1.1.0
      - numba==0.56.4
      - numpy==1.24.4
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.0.3
      - pathspec==0.12.1
      - pillow==9.5.0
      - polars==1.8.2
      - polygon3==3.0.9.1
      - portalocker==3.0.0
      - protobuf==4.21.2
      - psutil==7.1.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.7
      - pydot==4.0.1
      - pyparsing==3.1.4
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==3.9.7
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scipy==1.10.1
      - seaborn==0.13.2
      - six==1.17.0
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - timm==0.4.12
      - toml==0.10.2
      - tqdm==4.67.1
      - tzdata==2025.2
      - ultralytics==8.3.233
      - ultralytics-thop==2.0.18
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - yacs==0.1.8
prefix: /home/ylt1899/miniconda3/envs/deepsolo_wsl
